package com.example.chatapplication.data.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class ExerciseDto(
    @SerialName("id")
    val id: String? = null, // UUID auto-generated by DB

    @SerialName("name")
    val name: String, // exercise name

    @SerialName("description")
    val description: String = "", // defaults to empty string

    @SerialName("sets")
    val sets: Int = 3, // default number of sets

    @SerialName("reps")
    val reps: List<Int> = listOf(8, 10, 12) // default reps array
)
