package com.example.chatapplication.data.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class RoutineExerciseDto(
    @SerialName("id")
    val id: String? = null, // UUID auto-generated by DB

    @SerialName("routineId")
    val routineId: String, // references routine.id

    @SerialName("exerciseId")
    val exerciseId: String, // references exercise.id

    @SerialName("orderIndex")
    val orderIndex: Int // position of this exercise in the routine
)
