package com.example.chatapplication.data.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class RoutineDto(
    @SerialName("id")
    val id: String? = null, // auto-generated by DB if null

    @SerialName("userId")
    val userId: String, // UUID of the user who owns this routine

    @SerialName("name")
    val name: String, // routine name

    @SerialName("description")
    val description: String? = null // optional description
)
