package com.example.chatapplication.data.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class WorkoutSessionDto(
    @SerialName("id")
    val id: String? = null, // UUID auto-generated by DB

    @SerialName("userId")
    val userId: String, // references profile.id

    @SerialName("routineId")
    val routineId: String, // references routine.id

    @SerialName("startedAt")
    val startedAt: String? = null, // timestamp, defaults to now() in DB

    @SerialName("completedAt")
    val completedAt: String? = null // optional, nullable timestamp
)
