package com.example.chatapplication.data.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class WorkoutLogDto(
    @SerialName("id")
    val id: String? = null, // UUID auto-generated by DB

    @SerialName("sessionId")
    val sessionId: String, // references workout_session.id

    @SerialName("exerciseId")
    val exerciseId: String, // references exercise.id

    @SerialName("set")
    val set: Int, // which set this log is for

    @SerialName("weightUsed")
    val weightUsed: Int? = null, // optional weight used

    @SerialName("createdAt")
    val createdAt: String? = null // timestamp, defaults to now()
)
